version: "3"
services:
    keycloak_db:
        image: mariadb:10.4
        container_name: keycload_db
        env_file:
            - .env
            - auth.env
        networks:
            - auth
        volumes:
            - ./data/init-db.sh:/docker-entropint-initdb.d/init.sql
            - keycloak_db_data:/var/lib/mysql
    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        restart: ${RESTART}
        networks:
            - ${NETWORK}
            - auth
        env_file:
            - .env
            - auth.env
        # environment:
        #     - DB_VENDOR=${KC_DB_VENDOR}
        #     - DB_ADDR=${KC_DB_ADDR}
        #     - DB_USER=${KC_DB_USER}
        #     - DB_PASSWORD=${KC_DB_PASSWORD}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.auth.entrypoints=http"
            - "traefik.http.routers.auth.rule=Host(`auth.${TLD}`)"
            # - "traefik.http.routers.auth-secure.entrypoints=https"
            # - "traefik.http.routers.auth-secure.rule=Host(`auth.${TLD}`)"
            # - "traefik.http.routers.auth-secure.tls=true"
            # - "traefik.http.routers.auth-secure.tls.certresolver=http"
            # - "traefik.http.routers.auth-secure.service=auth"
            - "traefik.http.services.auth.loadbalancer.server.port=8080"
            - "traefik.docker.network=proxy"

volumes:
    keycloak_db_data:

networks:
    auth:
    proxy:
        external: true
