version: '3.2'

services:
    router:
        container_name: "mc_router"
        image: itzg/mc-router
        ports:
            - 25565:25565
        networks:
            - mc
        command: --mapping=vanilla.mc.draganczuk.cloud=mc_vanilla:25565,mc.draganczuk.cloud=mc_modded:25565
    mc_modded:
        container_name: "mc_modded"
        image: itzg/minecraft-server:multiarch
        environment:
            EULA: "true"
            MAX_MEMORY: 4G
            NABLE_RCON: "true"
            RCON_PASSWORD: "rcon"
            RCON_PORT: 28016
            TYPE: FTBA
            FTB_MODPACK_ID: 5
            ENABLE_AUTOPAUSE: "true"
            OPS: "draganczukp"
            LEVEL_TYPE: voidworld
            ALLOW_FLIGHT: "true"
        volumes:
            - ./data/modded:/data
        networks:
            - mc
    mc_vanilla:
        container_name: "mc_vanilla"
        image: itzg/minecraft-server:multiarch
        environment:
            EULA: "true"
            MAX_MEMORY: 4G
            ENABLE_RCON: "true"
            RCON_PASSWORD: "rcon"
            RCON_PORT: 28016
            OPS: "draganczukp"
            ALLOW_FLIGHT: "true"
        volumes:
            - ./data/vanilla:/data
        networks:
            - mc
    mc_rcon:
        image: itzg/rcon
        container_name: mc_rcon
        ports:
            - "4326:4326"
            - "4327:4327"
        volumes:
            - "rcon:/opt/rcon-web-admin/db"
        networks:
            - mc
        environment:
            RWA_PASSWORD: "rcon"
            RWA_ADMIN: "true"
            RWA_RCON_HOST: "mc"
            RWA_RCON_PASSWORD: "rcon"

networks:
    mc:

volumes:
    rcon:
