version: '3.2'

services:
  mc:
    container_name: "mc"
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MAX_MEMORY: 7G
      NABLE_RCON: "true"
      RCON_PASSWORD: "rcn"
      RCON_PORT: 28016
      TYPE: CURSEFORGE
      CF_SERVER_MOD: "modpack.zip"
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
  mc_rcon:
      image: itzg/rcon
      ports:
        - "4326:4326"
        - "4327:4327"
      volumes:
        - "rcon:/opt/rcon-web-admin/db"

volumes:
    rcon:
