version: '3'

services:
    nextcloud:
      container_name: nextcloud
      image: nextcloud
      volumes:
        - nextcloud:/var/www/html
      networks:
        - ${NETWORK}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cloud.entrypoints=http"
        - "traefik.http.routers.cloud.rule=Host(`cloud.${TLD}`)"
        - "traefik.http.middlewares.cloud-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.cloud.middlewares=cloud-https-redirect"
        - "traefik.http.routers.cloud-secure.entrypoints=https"
        - "traefik.http.routers.cloud-secure.rule=Host(`cloud.${TLD}`)"
        - "traefik.http.routers.cloud-secure.tls=true"
        - "traefik.http.routers.cloud-secure.tls.certresolver=http"
        - "traefik.http.routers.cloud-secure.service=cloud"
        - "traefik.http.services.cloud.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
      restart: ${RESTART}

networks:
    proxy:
      external: true

volumes:
  nextcloud:
