version: '3'

services:
    nc_db:
        image: mariadb:10.4
        container_name: nc_db
        networks:
            - nc
        env_file:
            - .env
            - nc.env
        volumes:
            - nc_db_data:/var/lib/mysql
        restart: ${RESTART}
    nextcloud:
      image: linuxserver/nextcloud
      container_name: nextcloud
      volumes:
          - ./data/nextcloud:/data
          - ./data/nextcloud.conf:/config
      # ports:
      #     - 443:443
      networks:
        - nc
        - proxy
      env_file:
          - .env
          - nc.env
      restart: ${RESTART}

networks:
    nc:
    proxy:
        external: true

volumes:
  nc_db_data:
  nextcloud:
