version: '3'

services:
    nc_db:
        image: mariadb
        container_name: nc_db
        networks:
            - nc
        env_file:
            - nc.env
        volumes:
            - nc_db_data:/var/lib/mysql
        restart: unless-stopped

    nextcloud:
        image: linuxserver/nextcloud
        container_name: nextcloud
        volumes:
            - ./data/data:/data
            - ./data/conf:/config
        networks:
            - nc
            - proxy
        env_file:
            - nc.env
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cloud.entrypoints=https"
            - "traefik.http.routers.cloud.rule=Host(`draganczuk.cloud`)"
            - "traefik.http.routers.cloud.tls=true"
            - "traefik.http.services.cloud.loadbalancer.server.port=443"
            - "traefik.http.services.cloud.loadbalancer.server.scheme=https"
            - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://draganczuk.cloud"
            - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' draganczuk.cloud *.draganczuk.cloud"
            - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
            - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
            - "traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=/.well-known/(card|cal)dav"
            - "traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=/remote.php/dav"
            - "traefik.http.middlewares.nextcloud-webfinger.redirectregex.regex=/.well-known/webfinger"
            - "traefik.http.middlewares.nextcloud-webfinger.redirectregex.replacement=/public.php?service=webfinger"
            - "traefik.http.routers.cloud.middlewares=nextcloud,nextcloud-redirect,nextcloud-webfinger"

    collabora:
        image: collabora/code
        container_name: collabora
        networks:
            # - nc
            - proxy
        ports:
            - 9980:9980
        env_file: code.env
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.office.entrypoints=https"
            - "traefik.http.routers.office.rule=Host(`office.draganczuk.cloud`)"
            - "traefik.http.routers.office.tls=true"
            - "traefik.http.services.office.loadbalancer.server.port=9980"
networks:
    nc:
    proxy:
        external: true

volumes:
  nc_db_data:
