version: "3"
services:
    searx:
        image: wonderfall/searx
        container_name: searx
        restart: unless-stopped
        networks:
            - proxy
        environment:
            BASE_URL: "https://search.draganczuk.cloud"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.search.entrypoints=https"
            - "traefik.http.routers.search.rule=Host(`search.draganczuk.cloud`)"
            - "traefik.http.routers.search.tls=true"
            # - "traefik.http.routers.search.tls.certresolver=acme"
            - "traefik.http.services.search.loadbalancer.server.port=8888"
            - "traefik.http.routers.search.middlewares=auth@file"
networks:
    proxy:
        external: true
