version: "3"
services:
  db:
      image: mariadb
      container_name: db
      # environment:
      #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
          - ./database:/var/lib/mysql
      networks:
          - proxy
      env_file:
          - ../vars.env
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      env_file:
          - ../vars.env
      environment:
          - PMA_HOST=db
          # - PMA_ARBITRARY=1
      restart: ${RESTART}
      volumes:
          - /sessions
      links:
          - db
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.phpmyadmin.entrypoints=http"
          - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${TLD}`)"
          - "traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-https-redirect"
          - "traefik.http.routers.phpmyadmin-secure.entrypoints=https"
          - "traefik.http.routers.phpmyadmin-secure.rule=Host(`phpmyadmin.${TLD}`)"
          - "traefik.http.routers.phpmyadmin-secure.tls=true"
          - "traefik.http.routers.phpmyadmin-secure.tls.certresolver=http"
          - "traefik.http.routers.phpmyadmin-secure.service=phpmyadmin"
          - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
          - "traefik.docker.network=proxy"
      networks:
          - ${NETWORK}

networks:
    proxy:
        external: true
