version: '2'
services:
  factorio:
    image: factoriotools/factorio:0.18
    container_name: factorio
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - ./data/factorio:/factorio
