version: "3"
services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        volumes:
            - ./data/config:/config
            - ./data/cache:/cache
            - /opt/volumes/media:/media
        networks:
            - proxy
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.entrypoints=https"
            - "traefik.http.routers.jellyfin.rule=Host(`media.draganczuk.cloud`)"
            - "traefik.http.routers.jellyfin.tls=true"
            - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
    proxy:
        external: true
