version: "2"
services:
  znc:
    image: linuxserver/znc
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./data:/config
    ports:
      - 6501:6501
    restart: ${RESTART}
    networks:
        - ${NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.irc.entrypoints=http"
      - "traefik.http.routers.irc.rule=Host(`irc.${TLD}`)"
      - "traefik.http.middlewares.irc-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.irc.middlewares=irc-https-redirect"
      - "traefik.http.routers.irc-secure.entrypoints=https"
      - "traefik.http.routers.irc-secure.rule=Host(`irc.${TLD}`)"
      - "traefik.http.routers.irc-secure.tls=true"
      - "traefik.http.routers.irc-secure.tls.certresolver=http"
      - "traefik.http.routers.irc-secure.service=irc"
      - "traefik.http.services.irc.loadbalancer.server.port=6501"
      - "traefik.docker.network=proxy"

networks:
    proxy:
        external: true
