version: '3'
services:
  terraria:
    image: beardedio/terraria:vanilla-latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      world: world.wld
    volumes:
      - ./data:/config
    tty: true
    stdin_open: true
